# Digital Habits and Smartphone Addiction Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

%matplotlib inline

In [ ]:
df.columns

In [2]:
df = pd.read_csv('Smartphone_Usage_And_Addiction_Analysis_7500_Rows.csv')

df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [3]:
df.describe()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label
count,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000
mean,26.568800,7.499912,3.273484,2.014183,3.242420,6.737561,134.257333,97.832400,9.243827,0.707733
std,5.197108,2.609188,1.585342,1.146039,1.600765,1.283605,66.586883,48.423349,2.718281,0.454835
min,18.000000,3.000000,0.500000,0.000000,0.500000,4.500000,20.000000,15.000000,3.580000,0.000000
25%,22.000000,5.220000,1.910000,1.020000,1.850000,5.630000,76.000000,55.000000,6.960000,0.000000
50%,27.000000,7.525000,3.270000,2.040000,3.230000,6.720000,134.000000,98.000000,9.260000,1.000000
75%,31.000000,9.810000,4.630000,2.990000,4.640000,7.840000,191.000000,140.000000,11.540000,1.000000
max,35.000000,12.000000,6.000000,4.000000,6.000000,9.000000,250.000000,180.000000,14.880000,1.000000

In [ ]:
print('Shape:',df.shape)

In [ ]:
cols = df.columns.to_list()
print('Column names:', cols)

**isna()** and **isnull()** both function the same way.

In [ ]:
print('Missing Values')
df.isna().sum()

We see that addiction level had so many missing values, we can check it out.

In [ ]:
df['addiction_level'].unique()

In [ ]:
names = ['john', 'sarah', 'jay']
age = [20, 39, 39]

for i, data in enumerate(zip(names, age), start=1):
    print(i, data)

In [ ]:
print('Columns names in DataSet:')
for i, col in enumerate(df.columns, 1):
    print(f"{i:2}: {col}") # Formats: number (2 spaces wide), colon, column name

## Basic Statistics

In [ ]:
# selects integer data type from the data set
df.select_dtypes(include='object').head()

In [ ]:
# numeric columns salary
numeric_cols = df.select_dtypes(include=[np.number]).columns
print('Summary Statistics:')
df[numeric_cols].describe()

- **.select_dtypes** -> Select columns based on data type
- **include=[np.number]** -> Include all numeric types (int, float)
- **.columns** -> Get just column names (not the data)

In [ ]:
objs = df.select_dtypes(include=['object']).columns
objs

We can drop **transaction_id** inplace since I don't see it will be used that much

In [ ]:
df.drop(columns='transaction_id', inplace=True)

In [ ]:
cat_cols = df.select_dtypes(include='object').columns

cat_cols

In [ ]:
user_id = [col for col in cat_cols if col == 'user_id']
user_id

In [ ]:
df[user_id].iloc[1:4]

In [ ]:
numeric_cols = df.select_dtypes(include=np.number).columns
numeric_cols

I can plot the average of all the numerics columns to see which one had the highest mean.

In [ ]:
ax = df[numeric_cols].mean().plot(kind='bar')
for container in ax.containers:
    ax.bar_label(container, fmt='%.2f', padding=3)
plt.xlabel(None)
plt.ylabel('Mean')
plt.title('Average of all Numeric Columns')
plt.xticks(rotation=45);

In [ ]:
len(numeric_cols)

# Key Questions to Explore  

## Q1:What is the average daily phone usage?

In [ ]:
df.columns

In [ ]:
# all statistical information about daily phone usage
df['daily_screen_time_hours'].describe()

In [ ]:
avg_screen_time = df['daily_screen_time_hours'].mean()

print(f"Average Screen Time: {avg_screen_time:.2f} hours.")

I have extracted these characteristics from the data set to explore them and find out the behavior of addicted people with these behaviors.

In [ ]:
areas_of_intrests = ['user_id', 'age', 'gender', 'social_media_hours', 'notifications_per_day', 'sleep_hours', 'stress_level', 'app_opens_per_day', 'weekend_screen_time']

In [ ]:
people_behavior = df[df['daily_screen_time_hours'] > avg_screen_time][areas_of_intrests]
people_behavior.reset_index(drop=True, inplace=True)

I want to group them in different age groups, but first I must check the highest and the lowest ages with in this data frame

In [ ]:
people_behavior['age'].agg(['max', 'min'])

In [ ]:
labels = ['18-22', '23-27', '28-31', '32-35']
bins = [18, 23, 28, 32, 35]

people_behavior['age_group'] = pd.cut(people_behavior['age'], labels=labels, bins=bins)

people_behavior.columns

In [ ]:
ax = sns.countplot(people_behavior, x='age_group')
for container in ax.containers:
    ax.bar_label(container)

plt.xticks(rotation=45)
plt.tight_layout()

In [ ]:
age_group_count = people_behavior.groupby('age_group')['age'].count()

In [ ]:
age_group_count.plot(kind='bar')
plt.title('Age Group Count of People with Interested behavior')
plt.xlabel('Count')
plt.ylabel('Age Groups')
plt.tight_layout()

I can explore the data of consumers whose daily screen time is above average and see their addiction level

In [ ]:
addiction_level_above_avr_screen_time = df[df['daily_screen_time_hours'] > avg_screen_time]['addiction_level']

ax = addiction_level_above_avr_screen_time.value_counts().plot(kind='bar')
for container in ax.containers:
    ax.bar_label(container)
plt.xlabel('Addiction Level')
plt.ylabel('Count')
plt.title('Count of Addiction Level above Average Daily Screen Hours')
plt.xticks(rotation=45)
plt.tight_layout()

In [ ]:
areas_of_intrests

In [ ]:
gender_count_people_behavior = people_behavior.groupby('gender')['user_id'].count()

gender_count_people_behavior.plot(kind='pie', autopct='%1.1f%%')
plt.title('Gender Distribution')
plt.ylabel('')  # Removes the default 'gender' y-label
plt.show()

## Q2: What is the gender distribution of the data set  

**Gender Distribution**

In [ ]:
df['gender'].value_counts()

In [ ]:
gender_counts = df['gender'].value_counts()
gender_counts.plot(kind='pie', autopct='%1.1f%%')
plt.title('Gender Distribution')
plt.ylabel('')  # Removes the default 'gender' y-label
plt.show()

In [ ]:
ax = sns.barplot(people_behavior, x='age_group', y='weekend_screen_time')
for container in ax.containers:
    ax.bar_label(container)

plt.title('Average Age Group Weekend Screen Time')
plt.ylabel('Mean')
plt.xlabel('Age Group')
plt.xticks(rotation=45);

In [ ]:
avg_age_group_weekend_screen_time = people_behavior.groupby('age_group')['weekend_screen_time'].mean()

ax = avg_age_group_weekend_screen_time.plot(kind='bar', color='orange')
for container in ax.containers:
    ax.bar_label(container)

plt.title('Average Age Group Weekend Screen Time')
plt.ylabel('Mean')
plt.xlabel('Age Group')
plt.xticks(rotation=45);

From this plot I can see that the age group average weekend screen time was evenly distributed among the different age groups.

In [ ]:
people_behavior.head()

In [ ]:
fig = px.line(people_behavior, x='age', y='app_opens_per_day')

fig.show()

In [ ]:
sns.lineplot(people_behavior, x='age', y='app_opens_per_day');

The line chart of app opens per day against age was plotted by it might not be that easy to visualize.

In [ ]:
people_behavior.groupby('age_group')['app_opens_per_day'].count()

In [ ]:
people_behavior.groupby('stress_level')[['sleep_hours', 'social_media_hours']].mean()

I can plot to see which gender had the highest count whose addiction level was above average.

In [ ]:
gender_counts_above_avr_daily_screen_hours = df[df['daily_screen_time_hours'] > avg_screen_time]['gender'].value_counts()

ax = gender_counts_above_avr_daily_screen_hours.plot(kind='bar')
for container in ax.containers:
    ax.bar_label(container)
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.title('Gender distribution Above Avarage Daily Screen Hours');

Males had a highest count with a total of 1316 and femals had a total count of 1241.

In [ ]:
type(gender_counts)

**Age Distribution**

In [ ]:
df['age'].count()

In [ ]:
print(df['age'].count() / 20)

In [ ]:
df['age'].describe()

In [ ]:
df['age'].plot(kind='hist', bins=20)

**Age Groups by Gender**

In [ ]:
print(df.groupby('gender')['age'].describe())

In [ ]:
# using plotly to visualize the gender distribution
fig = px.box(data_frame=df, y='age', x='gender')

fig.show()

In [ ]:
fig = px.histogram(data_frame=df, x='age', title='Histogram of Age')
fig.show()

In [ ]:
male_df = df[df['gender'] == 'Male']

fig = px.histogram(male_df, x='age', title='Histogram of Male distribution in the data set')

fig.show()

In [ ]:
gender_addicted_label = df.groupby('gender')['addicted_label'].value_counts()

# Unstack to get 'addicted_label' as columns
plot_data = gender_addicted_label.unstack()

# Plot grouped bars
plot_data.plot(kind='bar', figsize=(10,6))
plt.title('Addiction Status by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='Addicted')
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
sns.boxplot(y='gender', x='age', data=df)
plt.title('Gender Distribution');

**Addiction Level by Gender**

In [ ]:
df['addicted_label'].unique()

In [ ]:
plt.figure(figsize=(12,6))
ax = sns.countplot(x='gender', data=df, hue='addicted_label')
for container in ax.containers:
    ax.bar_label(container)
plt.title('Gender Count distribution of Addicted Label');

From this visualization we can conclude that males are more addicated than any other gender in the data set.

**Average Screen Time**

In [ ]:
df.columns

In [ ]:
avg_screen_time = df['daily_screen_time_hours'].mean()

print(f"Average Screen Time: {avg_screen_time:.2f} hours")

**Weekend vs Weekday Screen Time**

In [ ]:
print(f"Weekened Screen Time: {df['weekend_screen_time'].mean():.2f} hours")
print(f"Daily Screen Time: {df['daily_screen_time_hours'].mean():.2f} hours")

In [ ]:
weekly_screen_time = df[['weekend_screen_time', 'daily_screen_time_hours']].mean()
weekly_screen_time

In [ ]:
plt.figure(figsize=(10,6))
ax = sns.barplot(weekly_screen_time)
for container in ax.containers:
    ax.bar_label(container)

plt.ylabel('Mean Screen Time')
plt.xlabel(None)
plt.title('Average Weekly and Daily Screen Hours');

In [ ]:
fig = px.bar(weekly_screen_time)

fig.show()

**Screen Time by Addiction Level**

In [ ]:
cat_cols = df.select_dtypes(include=['object']).columns
cat_cols

In [ ]:
avg_daily_screen_time_addiction_level = df.groupby('addiction_level')['daily_screen_time_hours'].mean()
avg_daily_screen_time_addiction_level

In [ ]:
type(avg_daily_screen_time_addiction_level)

In [ ]:
plt.figure(figsize=(10,7))
avg_daily_screen_time_addiction_level.plot(kind='pie', autopct='%1.1f%%')
plt.title('Average Daily Screen Time Addiction Level')
plt.ylabel(None);

From this we can see that the daily addiction level is evenly distributed in the dataset.

In [ ]:
df.groupby('addiction_level')['daily_screen_time_hours'].describe()

In [ ]:
fig = px.box(df, x='daily_screen_time_hours', y='addiction_level')

fig.show()

In [ ]:
sns.boxplot(x='addiction_level', y='daily_screen_time_hours', data=df)
plt.title('Daily Screen Time vs Addiction Level');

## Activity Breakdown  

**Social Media vs Gaming vs Work**

In [ ]:
activities = ['social_media_hours', 'gaming_hours', 'work_study_hours']
activity_means = df[activities].mean()

In [ ]:
activity_means

In [ ]:
plt.figure(figsize=(12,6))
activity_means.plot(kind='pie', autopct='%1.1f%%')
plt.ylabel(None)
plt.title('Average Activity Means');

From this we can see which activity has the highest addiction rate, and that seem to be **social media hours** with a 38.4% mean.

In [ ]:
plt.bar(activity_means.index, activity_means.values)
plt.xticks(rotation=45)
plt.ylabel('Mean')
plt.title('Activity Means');

In [ ]:
df.columns

## Ploting a Histogram of Notifications per Day

In [ ]:
notifications_per_day = df['notifications_per_day']

In [ ]:
sns.histplot(notifications_per_day, bins=30)
plt.xlabel('No notifications per day')

plt.title("Count Of Notifications Per Day");

In [ ]:
fig = px.histogram(notifications_per_day)

fig.show()

In [ ]:
# Density plot
sns.kdeplot(notifications_per_day);

In [ ]:
gaming_hours = df['gaming_hours']

sns.kdeplot(gaming_hours);

In [ ]:
df.columns

**Activity Patterns by Gender**

In [ ]:
gender_activity_means = df.groupby('gender')[activities].mean()

sns.barplot(gender_activity_means);

In [ ]:
gender_activity_means.index

**Gaming Hours by Age**

In [ ]:
df['age'].agg(['count', 'max', 'min'])

In [ ]:
bins = [0, 15, 20, 25, 30, 35, 40]
labels = ['<15', '16-20', '21-25', '26-30', '31-35', '36+']

df['age_group'] = pd.cut(df['age'], labels=labels, bins=bins)

df['age_group'].value_counts()

In [ ]:
plt.figure(figsize=(10,6))
ax = sns.countplot(df, x='age_group')
for container in ax.containers:
    ax.bar_label(container)
plt.xlabel('Age Group')
plt.title('Age Group distribution Count');

In [ ]:
age_group_gaming_hours = df.groupby('age_group')['gaming_hours'].mean()
age_group_gaming_hours

In [ ]:
plt.figure(figsize=(10,6))
age_group_gaming_hours.plot(kind='bar')
plt.xlabel('Age Group')
plt.ylabel('Mean')
plt.title('Age Group mean of Gaming Hours');

In [ ]:
df.columns

**Average Notifications per Day**

In [ ]:
print(f"Average Notifications: {df['notifications_per_day'].mean():.0f} notifications per day")

**Notifications by Addiction Level**

In [ ]:
sns.boxplot(x='addicted_label', y='notifications_per_day', data=df);

**App Opens vs Screen Time**

In [ ]:
df.columns

In [ ]:
sns.scatterplot(x='app_opens_per_day', y='daily_screen_time_hours', hue='stress_level', data=df)
plt.xlabel('App Opens per Day')
plt.ylabel('Screen Time Hours');

## Sleep and Health Impact  

**Average Sleep Hours**

In [ ]:
print(f"Average sleep: {df['sleep_hours'].mean():.2f} hours")

**Screen Time Categories and Sleep**

In [ ]:
numeric_cols

In [ ]:
df['screen_category'] = pd.cut(
    df['daily_screen_time_hours'],
    bins=[0, 3, 6, 10, 24],
    labels=['Light', 'Moderate', 'Heavy', 'Extreme']
)

df.groupby('screen_category')['sleep_hours'].mean()

**Social Media Gender distribution**

In [ ]:
plt.figure(figsize=(10,7))
sns.barplot(x='age_group', y='social_media_hours', hue='gender', data=df)
plt.title('Gender average distribution of Social Media Hours');

In [ ]:
numeric_cols

## Stress & Academic Impact  

**Stress Level Distribution**

In [ ]:
df['stress_level'].value_counts().plot(kind='bar');

**Stress by Activity Type**

In [ ]:
df['stress_level'].unique()

In [ ]:
# Which activity is associated with high stress
high_stress = df[df['stress_level'] == 'High']
high_stress[['social_media_hours', 'gaming_hours', 'work_study_hours']].mean()

## Addiction Analysis  

**Addiction Level Distribution**

In [ ]:
# What percentage of users are addicted
df['addicted_label'].value_counts(normalize=True) * 100

**Addiction by Age Group**

In [ ]:
# Which age group has the highest addiction rate
pd.crosstab(df['age_group'], df['addicted_label'], normalize='index') * 100

**Addiction by Gender**

In [ ]:
# Which gender has higher addiction rates?
pd.crosstab(df['gender'], df['addicted_label'], normalize='index') * 100

**Users whose age are above 25**

In [ ]:
above_25_years = df[df['age'] > 25].copy()

In [ ]:
len(numeric_cols)

In [ ]:
above_25_years.columns

In [ ]:
plt.figure(figsize=(12,6))
sns.countplot(x='gender', hue='stress_level', data=above_25_years)
plt.title('Count Plot of Gender vs Stress Level');

In [ ]:
above_25_years.columns

In [ ]:
above_25_years['notifications_per_day'].describe()

**Users with more than 200 notifications per day**

In [ ]:
notifications_above_200 = above_25_years[above_25_years['notifications_per_day'] > 200]
notifications_below_100 = above_25_years[above_25_years['notifications_per_day'] < 100]

In [ ]:
df.columns

In [ ]:
sns.barplot(x='academic_work_impact', y='work_study_hours', hue='gender', data=notifications_above_200)
plt.title('Students above 200 notifications accademic work impact');

In [ ]:
sns.barplot(x='academic_work_impact', y='work_study_hours', hue='gender', data=notifications_below_100)
plt.title('Students below 100 notifications accademic work impact');

In [ ]:
notifications_above_200.drop(columns=['transaction_id', 'user_id'], inplace=True)

In [ ]:
notifications_above_200.reset_index(drop=True, inplace=True)
notifications_above_200

**High gaming users**

In [ ]:
high_gaming_users = notifications_above_200[notifications_above_200['gaming_hours'] > 2.0]
high_gaming_users

**Gender Distribution on High Gamers**

In [ ]:
high_gaming_users['gender'].value_counts()

In [ ]:
ax = sns.countplot(x='gender', data=high_gaming_users)

# add value labels on top of bar
for container in ax.containers:
    ax.bar_label(container)

plt.title('Gender Distribution of High Gamers');

In [ ]:
notifications_below_100.drop(columns=['transaction_id', 'user_id'], inplace=True)

In [ ]:
notifications_below_100.reset_index(drop=True, inplace=True)

In [ ]:
notifications_below_100

In [ ]:
ax = sns.countplot(x='gender', data=notifications_below_100)

# add labels at the top of bar
for container in ax.containers:
    ax.bar_label(container)

plt.title('Gender Distribution of Users below 100 Notifications');

In [ ]:
notifications_below_100['gender'].value_counts()

In [ ]:
notifications_below_100.columns

In [ ]:
notifications_below_100['stress_level'].unique()

In [ ]:
ax = sns.countplot(x='addicted_label', data=notifications_below_100)

for container in ax.containers:
    ax.bar_label(container)

plt.xlabel('Addicted Label')
plt.ylabel('Count')
plt.title('Count Plot of Addicted Label');

In [ ]:
sns.barplot(x='addicted_label', y='weekend_screen_time', data=notifications_below_100);

In [ ]:
notifications_below_100['age'].describe()

In [ ]:
notifications_below_100['age_group'] = pd.cut(
    notifications_below_100['age'], bins=[26, 28, 30, 32, 35],
    labels=['26-28', '29-30', '31-34', '35+']
)

In [ ]:
notifications_below_100.columns

In [ ]:
sns.set_style('darkgrid')

In [ ]:
notifications_below_100.groupby('age_group')['gaming_hours'].mean()

In [ ]:
ax = sns.barplot(x='age_group', y='gaming_hours', data=notifications_below_100)

for container in ax.containers:
    ax.bar_label(container)

plt.title('Average Gaming Hours for Various Age Groups')
plt.xlabel('Age Group')
plt.ylabel('Gaming Hours');

In [ ]:
notifications_below_100

In [ ]:
plt.figure(figsize=(10,6))
sns.scatterplot(x='social_media_hours', y='work_study_hours', data=notifications_below_100, hue='gender')
plt.title('Scatter Plot of Social Media Houra vs Work Study Hours')
plt.ylabel('Work Study Hours')
plt.xlabel('Socail Media Hours');

In [ ]:
notifications_below_100['social_media_hours'].describe()

In [ ]:
notifications_below_100['addiction_level'].unique()

In [ ]:
plt.figure(figsize=(10,6))
ax = sns.barplot(x='addiction_level', y='app_opens_per_day', data=notifications_below_100)

for container in ax.containers:
    ax.bar_label(container)
    
plt.xlabel('Socail Media Hours')
plt.ylabel('Average Appes Opened')
plt.title('Social Media Hours by Apps Opened');

In [ ]:
df.columns

In [ ]:
df.groupby('academic_work_impact')['notifications_per_day'].mean()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.describe(include='all')

In [ ]:
cat_col = ['gender', 'stress_level', 'academic_work_impact', 'addiction_level']

for col in cat_col:
    print(f"{col:10s}: {df[col].value_counts().to_dict()}")

In [ ]:
df.columns.to_list()