In [1]:
import os

print(os.listdir())

['E_sales.ipynb', 'order_items.csv', 'ecommerce_sales_customer_analytics_150k.csv', 'dataset_statistics.csv', '.ipynb_checkpoints', 'customer_master.csv', 'product_catalog.csv']

# Loading the data

In [1]:
import pandas as pd

In [21]:
order_items = pd.read_csv('order_items.csv')
customer_master = pd.read_csv('customer_master.csv')
product_catalog = pd.read_csv('product_catalog.csv')

In [15]:
print(customer_master.shape)
customer_master.info()

(25000, 11)
<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  str
 1   customer_name              25000 non-null  str
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  str
 4   customer_segment           25000 non-null  str
 5   customer_city              25000 non-null  str
 6   customer_state             25000 non-null  str
 7   customer_country           25000 non-null  str
 8   region                     25000 non-null  str
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 MB

In [16]:
print(order_items.shape)
order_items.info()

(397569, 12)
<class 'pandas.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  str
 1   product_id           397569 non-null  str
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), str(2)
memory usage: 36.4 MB

In [10]:
print(product_catalog.shape)
product_catalog.head()

(1175, 9)

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [12]:
product_catalog.info()

<class 'pandas.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   str
 1   product_name         1175 non-null   str
 2   product_category     1175 non-null   str
 3   product_subcategory  1175 non-null   str
 4   brand                1175 non-null   str
 5   supplier             1175 non-null   str
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), str(6)
memory usage: 82.7 KB

In [19]:
ecommerce_sales_anaytics.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [20]:
ecommerce_sales_anaytics.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB